version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: hypermarket-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: hypermarket
      POSTGRES_USER: hypermarket
      POSTGRES_PASSWORD: hypermarket
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U hypermarket -d hypermarket']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: hypermarket-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: ['redis-server', '--appendonly', 'yes']
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
