export enum ErrorCode {
  ValidationFailed = 'validation_failed',
  Unauthorized = 'unauthorized',
  Forbidden = 'forbidden',
  NotFound = 'not_found',
  Conflict = 'conflict',
  RateLimited = 'rate_limited',
  IdempotencyConflict = 'idempotency_conflict',
  TenantResolutionFailed = 'tenant_resolution_failed',
  PublishValidationFailed = 'publish_validation_failed',
  PaymentProviderError = 'payment_provider_error',
  NotificationFailed = 'notification_failed',
  InternalError = 'internal_error',
  NotImplemented = 'not_implemented',
  DevFeatureDisabled = 'dev_feature_disabled',
  DevOtpNotFound = 'dev_otp_not_found',
  DevForbidden = 'dev_forbidden',

  // TMP (Templates) module codes
  TemplateNotFound = 'template_not_found',
  TemplateVersionNotFound = 'template_version_not_found',

  // TEN (Tenancy & Storefront Configuration) module codes
  TenantSlugInvalid = 'tenant_slug_invalid',
  TenantSlugTaken = 'tenant_slug_taken',
  TenantNotFound = 'tenant_not_found',
  TenantSuspended = 'tenant_suspended',
  TenantArchived = 'tenant_archived',
  TenantDomainInvalid = 'tenant_domain_invalid',
  TenantDomainTaken = 'tenant_domain_taken',
  TenantDomainNotFound = 'tenant_domain_not_found',
  TenantSettingsInvalid = 'tenant_settings_invalid',
  TenantMembershipExists = 'tenant_membership_exists',
  TenantMembershipNotFound = 'tenant_membership_not_found',
  TenantMembershipRevoked = 'tenant_membership_revoked',
  TenantMembershipRoleInvalid = 'tenant_membership_role_invalid',
  TenantMemberSelfRevokeForbidden = 'tenant_member_self_revoke_forbidden',
  TenantLastOwnerRevokeForbidden = 'tenant_last_owner_revoke_forbidden',
  TenantLastOwnerRoleChangeForbidden = 'tenant_last_owner_role_change_forbidden',
  TenantMemberTargetNotFound = 'tenant_member_target_not_found',
  TenantMemberAlreadyRevoked = 'tenant_member_already_revoked',
  TenantAccessForbidden = 'tenant_access_forbidden',
  TenantDbFailure = 'tenant_db_failure',

  // PUB (Publishing) module codes
  ConfigInvalidPayload = 'config_invalid_payload',
  ConfigSchemaMismatch = 'config_schema_mismatch',
  ConfigNotFound = 'config_not_found',
  ConfigNotOwnedByTenant = 'config_not_owned_by_tenant',
  ConfigAlreadyActive = 'config_already_active',
  ConfigNotDraft = 'config_not_draft',
  ConfigVersionConflict = 'config_version_conflict',
  PublishFailed = 'publish_failed',
  RollbackFailed = 'rollback_failed',
  RevalidationDispatchFailed = 'revalidation_dispatch_failed',

  // CAT (Catalog) module codes
  CatalogProductNotFound = 'catalog_product_not_found',
  CatalogCategoryNotFound = 'catalog_category_not_found',
  CatalogSlugInvalid = 'catalog_slug_invalid',
  CatalogSlugTaken = 'catalog_slug_taken',
  CatalogPriceInvalid = 'catalog_price_invalid',
  CatalogCurrencyNotSupported = 'catalog_currency_not_supported',
  CatalogInventoryRuleViolation = 'catalog_inventory_rule_violation',
  CatalogValidationFailed = 'catalog_validation_failed',

  // IAA (Identity and Access) module codes
  AuthInvalidPhoneFormat = 'auth_invalid_phone_format',
  AuthPhoneCountryNotSupported = 'auth_phone_country_not_supported',
  AuthOtpRateLimitedPhone = 'auth_otp_rate_limited_phone',
  AuthOtpRateLimitedIp = 'auth_otp_rate_limited_ip',
  AuthChallengeNotFound = 'auth_challenge_not_found',
  AuthChallengeExpired = 'auth_challenge_expired',
  AuthChallengeLocked = 'auth_challenge_locked',
  AuthChallengeConsumed = 'auth_challenge_consumed',
  AuthChallengePhoneMismatch = 'auth_challenge_phone_mismatch',
  AuthOtpInvalid = 'auth_otp_invalid',
  AuthUserSuspended = 'auth_user_suspended',
  AuthSessionIssueFailed = 'auth_session_issue_failed',
  AuthMissingToken = 'auth_missing_token',
  AuthInvalidToken = 'auth_invalid_token',
  AuthSessionNotFound = 'auth_session_not_found',
  AuthSessionExpired = 'auth_session_expired',
  AuthSessionRevoked = 'auth_session_revoked',
  AuthTenantMembershipMissing = 'auth_tenant_membership_missing',
  AuthTenantMembershipRevoked = 'auth_tenant_membership_revoked',
  AuthProviderAuthFailed = 'auth_provider_auth_failed',
  AuthProviderRateLimited = 'auth_provider_rate_limited',
  AuthProviderUnavailable = 'auth_provider_unavailable',
  AuthDbFailure = 'auth_db_failure'
}
