export enum ErrorCode {
  ValidationFailed = 'validation_failed',
  Unauthorized = 'unauthorized',
  Forbidden = 'forbidden',
  NotFound = 'not_found',
  Conflict = 'conflict',
  RateLimited = 'rate_limited',
  IdempotencyConflict = 'idempotency_conflict',
  TenantResolutionFailed = 'tenant_resolution_failed',
  PublishValidationFailed = 'publish_validation_failed',
  PaymentProviderError = 'payment_provider_error',
  NotificationFailed = 'notification_failed',
  InternalError = 'internal_error',
  NotImplemented = 'not_implemented',
  DevFeatureDisabled = 'dev_feature_disabled',
  DevOtpNotFound = 'dev_otp_not_found',
  DevForbidden = 'dev_forbidden',

  // TMP (Templates) module codes
  TemplateNotFound = 'template_not_found',
  TemplateVersionNotFound = 'template_version_not_found',

  // TEN (Tenancy & Storefront Configuration) module codes
  TenantSlugInvalid = 'tenant_slug_invalid',
  TenantSlugTaken = 'tenant_slug_taken',
  TenantNotFound = 'tenant_not_found',
  TenantSuspended = 'tenant_suspended',
  TenantArchived = 'tenant_archived',
  TenantDomainInvalid = 'tenant_domain_invalid',
  TenantDomainTaken = 'tenant_domain_taken',
  TenantDomainNotFound = 'tenant_domain_not_found',
  TenantSettingsInvalid = 'tenant_settings_invalid',
  TenantMembershipExists = 'tenant_membership_exists',
  TenantMembershipNotFound = 'tenant_membership_not_found',
  TenantMembershipRevoked = 'tenant_membership_revoked',
  TenantMembershipRoleInvalid = 'tenant_membership_role_invalid',
  TenantMemberSelfRevokeForbidden = 'tenant_member_self_revoke_forbidden',
  TenantLastOwnerRevokeForbidden = 'tenant_last_owner_revoke_forbidden',
  TenantLastOwnerRoleChangeForbidden = 'tenant_last_owner_role_change_forbidden',
  TenantMemberTargetNotFound = 'tenant_member_target_not_found',
  TenantMemberAlreadyRevoked = 'tenant_member_already_revoked',
  TenantAccessForbidden = 'tenant_access_forbidden',
  TenantDbFailure = 'tenant_db_failure',

  // PUB (Publishing) module codes
  ConfigInvalidPayload = 'config_invalid_payload',
  ConfigSchemaMismatch = 'config_schema_mismatch',
  ConfigNotFound = 'config_not_found',
  ConfigNotOwnedByTenant = 'config_not_owned_by_tenant',
  ConfigAlreadyActive = 'config_already_active',
  ConfigNotDraft = 'config_not_draft',
  ConfigVersionConflict = 'config_version_conflict',
  PublishFailed = 'publish_failed',
  RollbackFailed = 'rollback_failed',
  RevalidationDispatchFailed = 'revalidation_dispatch_failed',

  // CAT (Catalog) module codes
  CatalogProductNotFound = 'catalog_product_not_found',
  CatalogCategoryNotFound = 'catalog_category_not_found',
  CatalogSlugInvalid = 'catalog_slug_invalid',
  CatalogSlugTaken = 'catalog_slug_taken',
  CatalogPriceInvalid = 'catalog_price_invalid',
  CatalogCurrencyNotSupported = 'catalog_currency_not_supported',
  CatalogInventoryRuleViolation = 'catalog_inventory_rule_violation',
  CatalogValidationFailed = 'catalog_validation_failed',

  // MED (Media & Assets) module codes
  MediaMimeNotAllowed = 'media_mime_not_allowed',
  MediaFileTooLarge = 'media_file_too_large',
  MediaQuotaExceeded = 'media_quota_exceeded',
  MediaUploadTokenFailed = 'media_upload_token_failed',
  MediaAssetNotFound = 'media_asset_not_found',
  MediaStorageKeyMismatch = 'media_storage_key_mismatch',
  MediaConfirmFailed = 'media_confirm_failed',
  MediaDeleteForbidden = 'media_delete_forbidden',
  MediaDeleteFailed = 'media_delete_failed',
  MediaValidationFailed = 'media_validation_failed',

  // ORD (Orders) module codes
  OrderIdempotencyConflict = 'order_idempotency_conflict',
  OrderInvalidItems = 'order_invalid_items',
  OrderProductNotFound = 'order_product_not_found',
  OrderVariantNotFound = 'order_variant_not_found',
  OrderProductNotAvailable = 'order_product_not_available',
  OrderQuantityInvalid = 'order_quantity_invalid',
  OrderFulfillmentInvalid = 'order_fulfillment_invalid',
  OrderTotalMismatchInternal = 'order_total_mismatch_internal',
  OrderInvalidStateTransition = 'order_invalid_state_transition',
  OrderNotFound = 'order_not_found',
  OrderValidationFailed = 'order_validation_failed',

  // PAY (Payments) module codes
  PaymentProviderConfigInvalid = 'payment_provider_config_invalid',
  PaymentProviderUnavailable = 'payment_provider_unavailable',
  PaymentPhoneInvalid = 'payment_phone_invalid',
  PaymentOrderNotFound = 'payment_order_not_found',
  PaymentOrderNotPayable = 'payment_order_not_payable',
  PaymentIntentNotFound = 'payment_intent_not_found',
  PaymentInvalidStateTransition = 'payment_invalid_state_transition',
  PaymentWebhookSignatureInvalid = 'payment_webhook_signature_invalid',
  PaymentWebhookParseFailed = 'payment_webhook_parse_failed',
  PaymentIdempotencyConflict = 'payment_idempotency_conflict',
  PaymentReconciliationFailed = 'payment_reconciliation_failed',
  PaymentDbFailure = 'payment_db_failure',
  PaymentWebhookHashMissing = 'payment_webhook_hash_missing',
  PaymentWebhookHashMismatch = 'payment_webhook_hash_mismatch',
  PaymentProviderRejectedRequest = 'payment_provider_rejected_request',
  PaymentProviderRateLimited = 'payment_provider_rate_limited',
  PaymentProviderAuthFailed = 'payment_provider_auth_failed',
  PaymentTransactionVerificationFailed = 'payment_transaction_verification_failed',
  PaymentTransactionMismatch = 'payment_transaction_mismatch',

  // NOT (Notifications) module codes
  NotTemplateNotFound = 'not_template_not_found',
  NotTemplatePayloadInvalid = 'not_template_payload_invalid',
  NotRecipientInvalid = 'not_recipient_invalid',
  NotProviderUnavailable = 'not_provider_unavailable',
  NotProviderAuthFailed = 'not_provider_auth_failed',
  NotProviderRateLimited = 'not_provider_rate_limited',
  NotSendFailedRetryable = 'not_send_failed_retryable',
  NotSendFailedNonRetryable = 'not_send_failed_non_retryable',
  NotJobNotFound = 'not_job_not_found',
  NotJobDedupeConflict = 'not_job_dedupe_conflict',
  NotDbFailure = 'not_db_failure',

  // FUL (Fulfillment) module codes
  FulNoFulfillmentModeEnabled = 'ful_no_fulfillment_mode_enabled',
  FulDeliveryEnabledWithoutZones = 'ful_delivery_enabled_without_zones',
  FulSettingsInvalid = 'ful_settings_invalid',
  FulZoneNotFound = 'ful_zone_not_found',
  FulZoneInactive = 'ful_zone_inactive',
  FulZoneNameTaken = 'ful_zone_name_taken',
  FulZoneInvalid = 'ful_zone_invalid',
  FulStoreClosed = 'ful_store_closed',
  FulFulfillmentSelectionInvalid = 'ful_fulfillment_selection_invalid',
  FulDeliveryMinOrderNotMet = 'ful_delivery_min_order_not_met',
  FulDeliveryNotAvailable = 'ful_delivery_not_available',
  FulPickupNotAvailable = 'ful_pickup_not_available',

  // IAA (Identity and Access) module codes
  AuthInvalidPhoneFormat = 'auth_invalid_phone_format',
  AuthPhoneCountryNotSupported = 'auth_phone_country_not_supported',
  AuthOtpRateLimitedPhone = 'auth_otp_rate_limited_phone',
  AuthOtpRateLimitedIp = 'auth_otp_rate_limited_ip',
  AuthChallengeNotFound = 'auth_challenge_not_found',
  AuthChallengeExpired = 'auth_challenge_expired',
  AuthChallengeLocked = 'auth_challenge_locked',
  AuthChallengeConsumed = 'auth_challenge_consumed',
  AuthChallengePhoneMismatch = 'auth_challenge_phone_mismatch',
  AuthOtpInvalid = 'auth_otp_invalid',
  AuthUserSuspended = 'auth_user_suspended',
  AuthSessionIssueFailed = 'auth_session_issue_failed',
  AuthMissingToken = 'auth_missing_token',
  AuthInvalidToken = 'auth_invalid_token',
  AuthSessionNotFound = 'auth_session_not_found',
  AuthSessionExpired = 'auth_session_expired',
  AuthSessionRevoked = 'auth_session_revoked',
  AuthTenantMembershipMissing = 'auth_tenant_membership_missing',
  AuthTenantMembershipRevoked = 'auth_tenant_membership_revoked',
  AuthProviderAuthFailed = 'auth_provider_auth_failed',
  AuthProviderRateLimited = 'auth_provider_rate_limited',
  AuthProviderUnavailable = 'auth_provider_unavailable',
  AuthDbFailure = 'auth_db_failure'
}
